### ISSUE TITLE
麻烦修复，大神

### ISSUE THREAD

**Issue by keiweila** [wujunwei/php-extension-export#1]
![image](https://user-images.githubusercontent.com/27436327/54100517-b8ed7c00-43f9-11e9-8c1d-4fd06738fd41.png)
![image](https://user-images.githubusercontent.com/27436327/54100523-bf7bf380-43f9-11e9-9680-ae11367d2c66.png)

**Comment by wumengkang** [comment]
直接提pr给他呀

**Comment by wujunwei** [comment]
已修复
